export const EstadoTurnoEnum = Object.freeze({
  DISPONIBLE: "DISPONIBLE",
  RESERVADO: "RESERVADO",
  CONFIRMADO: "CONFIRMADO",
  CANCELADO: "CANCELADO",
  REALIZADO: "REALIZADO",
  PENDIENTECAMBIO: "PENDIENTECAMBIO",
});