services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    environment:
      SERVER_PORT: 3000
      MONGODB_URI: mongodb+srv://fandino:fandino1234@cluster0.yenb7oc.mongodb.net 
      MONGODB_DB_NAME: Sweet-Medical-Cloud
      ALLOWED_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
  